
<a href="http://www.cosmostat.org/" target="_blank"><img align="left" width="300" src="http://www.cosmostat.org/wp-content/uploads/2017/07/CosmoStat-Logo_WhiteBK-e1499155861666.png" alt="CosmoStat Logo"></a>
<br>
<br>
<br>
<br>

# Numpy, Scipy, Pandas and other useful tools in a scientist's toolbag

---

> Author: <a href="http://www.cosmostat.org/people/santiago-casas" target="_blank" style="text-decoration:none; color: #F08080">Santiago Casas</a>  
> Email: <a href="mailto:santiago.casas@cea.fr" style="text-decoration:none; color: #F08080">santiago.casas@cea.fr</a>  
> Year: 2019  
> Version: 1.0

---
<br>



So far we have seen how to use and define *lists, dictionaries, functions* and some other *pythonic* tools. However, in scientific research one often needs more than simple algorithms and one needs specialized libraries for working with arrays, math functions, databases and graphics.

## Let's start by importing the necessary libraries

In [2]:
import numpy

It more convenient to assign the numpy package contents to an alias to avoid having longer expressions.

In [3]:
import numpy as np

In this example the **`as`** statement assigns the numpy package contents to the object `np`.

---

## Arrays

### The Basics

The most essential numpy object is the numpy array (<a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html" target="_blank">numpy.ndarray</a>).

In [93]:
# a is a list
a = [1, 2, 3, 4]
print('a is', type(a))

# b is a numpy array
b = np.array(a)
print('b is', type(b))

a is <class 'list'>
b is <class 'numpy.ndarray'>


Accessing and printing a single entry works exactly the same.

In [94]:
print('first element of a is', a[0])
print('first element of b is', b[0])

first element of a is 1
first element of b is 1


In [96]:
print('last element of a is', a[-1])
print('last element of b is', b[-1])

last element of a is 4
last element of b is 4


However, their printed forms are slightly different.

In [13]:
print('list: ', a)
print('np array: ',b)

list:  [1, 2, 3, 4]
np array:  [1 2 3 4]


Moreover, while lists can contain different object types

In [14]:
a = [1, 1.0, 'a', True]
print(a)

[1, 1.0, 'a', True]


numpy arrays are of a single type only, which is one of the reasons why they are so efficient.

---




For example, in this case it will convert all entries to strings (upcasting)

In [17]:
np.array(a)

array(['1', '1.0', 'a', 'True'], dtype='<U32')

Or in this case, all entries to floats

In [18]:
np.array([1, 2.5, 23, 100.0, np.pi])

array([  1.        ,   2.5       ,  23.        , 100.        ,
         3.14159265])

One can also specify the type directly with the optional argument **dtype** and the entries will be converted to the specified type.

In [21]:
np.array([1, 2.5, 23, 100.0, np.pi], dtype='int32')

array([  1,   2,  23, 100,   3], dtype=int32)

Did you notice the $\pi$ constant in the list above? Here you can find a list of available (<a href="https://www.numpy.org/devdocs/reference/constants.html" target="_blank">constants</a>). Another one useful in science is

In [28]:
#Euler's constant
np.e

2.718281828459045

## Creating arrays from scratch

Sometimes it is useful to create a numpy array in a fast way from scratch. Numpy offers several neat methods.

### Zeros and Ones

In [61]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
# Create a length-5 floating-point array filled with ones
np.ones(5, dtype=float)

array([1., 1., 1., 1., 1.])

### A range and linspace

One of the most useful arrays for everyday scientific work is to create arrays that contain evenly-spaced numbers within an interval. 

In [68]:
#A range of floats up to 3.0 with default step 1.0
print(np.arange(3.0))
# A range from start to stop, with a given step
print(np.arange(5.0, 405., 50))

[0. 1. 2.]
[  5.  55. 105. 155. 205. 255. 305. 355.]


> **<font color='red'>NOTE:</font>** Note that with **`arange`** the endpoint is not included !

Remember to check the documentation within the Jupyter notebook running on a cell: **`?np.arange`**

If one needs to specify the number of samples and also include the endpoint, then linspace is the right tool. It even contains an optional argument `endpoint`, which defaults to `True`.

In [80]:
#Three floats evenly spaced in the interval 0. to 3. 
print(np.linspace(0.,3.,3))

[0.  1.5 3. ]


In [74]:
#With endpoint=False, we get the same behavior as `np.arange`
print(np.linspace(0.,3.,3, endpoint=False))

[0. 1. 2.]


In [79]:
#default number of samples is 50
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

Another important array for scientists is a **logaritmically-spaced** interval. The default logarithm is base 10, but that can be changed with the `base` optional argument. The initial and final values of the interval have to be specified in their logarithms.

In [105]:
# A log10-spaced interval from 10^-2 to 10^3 of size 5.
np.logspace(-2, 3, 5)

array([1.00000000e-02, 1.77827941e-01, 3.16227766e+00, 5.62341325e+01,
       1.00000000e+03])

Applying a $\log_{10}$ on the whole array shows that it is indeed log-spaced.

In [106]:
np.log10(np.logspace(-2, 3, 5))

array([-2.  , -0.75,  0.5 ,  1.75,  3.  ])

> **Notice** how we are using `numpy` internal functions, called uFuncs to calculate properties on the entire array. We will explain that better a bit later.

In [173]:
#A ln-spaced interval from e^-1 to e^4 of size 4.
e_array = np.logspace(np.log(np.exp(-1)), np.log(np.exp(4)), 4, base=np.e)

> **Puzzle 1:** What is the ouput of `np.log(e_array)[-1]` ?

In [178]:
#Uncomment to see the answer
#print('the result is: ', np.log(e_array)[-1])

### Multi-dimensional arrays

Arrays can also be multi-dimensional. And their shape can be specified at creation.

In [34]:
#2-dimensional array of size 3x5
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Creating the ***identity*** matrix of size 5

In [35]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

`np.eye` is a generalization of the identity, with arguments `numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')`. `N` is the number of rows of the array, `M` defaults to `N` and is the number of columns, while `k` shifts the diagonal by a positive or negative integer with respect to the main diagonal. The other arguments can be looked up in the documentation.

In [38]:
#rectangular matrix
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [41]:
#shifted diagonal
np.eye(5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Sometimes one just needs an array with garbage numbers which is to be filled later on. `np.empty` does the job:

In [49]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty((3,6))

array([[4.64181043e-310, 4.64181043e-310, 4.64181043e-310,
        4.64181043e-310, 4.64181043e-310, 4.64181043e-310],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 6.92638494e-310]])

Very useful in science is the creation of arrays with **random numbers** following a given distribution. Check the extensive documentation of (<a href="https://www.numpy.org/devdocs/reference/random/index.html?highlight=random#module-numpy.random" target="_blank">numpy.random</a>) for much more information on all the available methods.

In [140]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.28175235,  0.42381972,  0.3933318 ],
       [ 0.25981525,  0.34797576, -0.29678152],
       [-0.22976017,  1.07143505,  0.56506516]])

In [146]:
# Create a 6x6 array of uniformly distributed
# random integers between 0 and 10
rand_mat = np.random.randint(0, 10, (6, 6))
print(rand_mat[:,0])

[4 8 6 6 5 6]


To construct multi-dimensional arrays, one can also reshape 1-dimensional arrays, using the useful method `reshape(i,j)`. The arguments indicate the rows and the columns of the new array.

In [148]:
# Convert 1-dim array into 2x2 matrix
e_array.reshape((2,2))

array([[ 0.36787944,  1.94773404],
       [10.3122585 , 54.59815003]])

In [149]:
# Reshape a 2-dim array
rand_mat.reshape(9,4)

array([[4, 4, 4, 2],
       [6, 9, 8, 6],
       [2, 7, 7, 2],
       [6, 6, 1, 5],
       [8, 3, 6, 5],
       [2, 1, 5, 5],
       [5, 3, 3, 6],
       [0, 0, 6, 7],
       [8, 4, 9, 6]])

If the second argument is `-1` then the size of the second axis is inferred from the previous array.

In [150]:
rand_mat.reshape(3,-1)

array([[4, 4, 4, 2, 6, 9, 8, 6, 2, 7, 7, 2],
       [6, 6, 1, 5, 8, 3, 6, 5, 2, 1, 5, 5],
       [5, 3, 3, 6, 0, 0, 6, 7, 8, 4, 9, 6]])

> **Puzzle 2:** The attribute `shape` returns the shape of a numpy array in the form of a tuple. What is the output of `rand_mat.reshape(2,-1).shape[1]` ?

In [153]:
#Uncomment to see the answer
#print('the answer is: ', rand_mat.reshape(2,-1).shape[1])

Another useful method is `np.ravel` which is roughly the "inverse" of reshape in this case. It returns a flattened 1-d array from a 2-d array, equivalent in most cases to `np.flatten`.

In [322]:
e_array.reshape((2,2)).ravel()

array([ 0.36787944,  1.94773404, 10.3122585 , 54.59815003])

In [323]:
e_array.reshape((2,2)).flatten()

array([ 0.36787944,  1.94773404, 10.3122585 , 54.59815003])

And for scientific purposes, the ***transpose*** is a very important attribute

In [325]:
e_array.reshape((2,2)).T

array([[ 0.36787944, 10.3122585 ],
       [ 1.94773404, 54.59815003]])

In [327]:
(e_array.reshape((2,2)).T)[0,1]==(e_array.reshape((2,2)))[1,0]

True

Other available attributes are:

In [154]:
print("Number of dimensions, ndim: ", rand_mat.ndim)
print("Array shape:", rand_mat.shape)
print("Array size: ", rand_mat.size)

Number of dimensions, ndim:  2
Array shape: (6, 6)
Array size:  36


## Slicing and accessing elements

As you might now, slicing works for lists, using the `:` operator

In [159]:
list = [1,2,3,4,5,6]

In [160]:
#Take the first two elements of the list
list[:2]

[1, 2]

In [162]:
print(list[2:])
#Omitting the number after the semicolon is equivalent to indicating the list size:
list[2:6] ==  list[2:]

[3, 4, 5, 6]


True

In [238]:
#Reverse the list
list[::-1]

[6, 5, 4, 3, 2, 1]

Same works for numpy arrays. Here we extend our `e_array` by concatenating it with the useful method `concatenate`, three times.

In [169]:
extended_array = np.concatenate([e_array, e_array, e_array])
print(extended_array)

[ 0.36787944  1.94773404 10.3122585  54.59815003  0.36787944  1.94773404
 10.3122585  54.59815003  0.36787944  1.94773404 10.3122585  54.59815003]


To obtain three times the same number, we just need to get every fourth element

In [234]:
extended_array[::4]

array([0.36787944, 0.36787944, 0.36787944])

> **Puzzle 3:** Obtain the array `[4., 4., 4.]` from `extended_array` by using slicing and `log`.

In [321]:
#Answer Puzzle 3:
##np.log(extended_array[3::4])

> **<font color='red'>NOTE:</font>** Slicing performs a view of the element and not a copy !

### Slicing: View vs. Copy

In [305]:
# Nested list comprehension
array2d = np.array([[ ii+jj for jj in range((ii-1)*4,(ii-1)*4+5)] for ii in range(1,1+4)])
print(array2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


For multi-dimensional arrays, the different axis are accessed by separating the slices with commas.

In [306]:
#All rows, every other column
array2d[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

In [307]:
#Fourth row, all columns
array2d[3,:]

array([16, 17, 18, 19, 20])

In [308]:
#Obtain shape
array2d.shape

(4, 5)

In [309]:
#Obtain central array
array2d_center=array2d[1:array2d.shape[0]-1, 1:array2d.shape[1]-1]
print(array2d_center)

[[ 7  8  9]
 [12 13 14]]


In [310]:
#Now if we modify this subarray, we'll see that the original array is changed! 
array2d_center[0,0]=1001.5

In [311]:
print(array2d_center)

[[1001    8    9]
 [  12   13   14]]


In [312]:
print(array2d)

[[   1    2    3    4    5]
 [   6 1001    8    9   10]
 [  11   12   13   14   15]
 [  16   17   18   19   20]]


> **<font color='red'>NOTE:</font>** Notice not only the changed big array, but also how numpy converted automatically the type of the variable to `int`, to match the other variable types !

From the `Python Data Science Handbook`: This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

However, if we don't want this behavior, because it can be confusing and introduce possible bugs (believe me, it has happened to me), we can use the `copy` method.

In [313]:
sub_array = array2d[2:,:3].copy()
print(sub_array)

[[11 12 13]
 [16 17 18]]


In [314]:
#Modify an element of the subarray
sub_array[1,1] = 999
print(sub_array)

[[ 11  12  13]
 [ 16 999  18]]


Now the large array is not touched:

In [315]:
print(array2d)

[[   1    2    3    4    5]
 [   6 1001    8    9   10]
 [  11   12   13   14   15]
 [  16   17   18   19   20]]


Useful trick: Many elements of the large array can be modified through the small array using slicing.

In [316]:
array2d_center[:2,:2]=[[42,42],[42,42]]

In [317]:
print(array2d)

[[ 1  2  3  4  5]
 [ 6 42 42  9 10]
 [11 42 42 14 15]
 [16 17 18 19 20]]


> **Puzzle 4:** Change all the last two columns by zeros using slicing, np.shape and np.zeros (assuming you don't know the size of the array beforehand)

In [319]:
#Answer Puzzle 4:
#array2d[:,-2:]=np.zeros((array2d.shape[0],2))
#print(array2d)

## Numpy integrated universal functions

The power of **numpy** lies in its speed and efficiency in performing operations on large arrays.

Functions that operate on the entire array are called ***universal functions*** or for short, uFuncs.

### Arithmetic

In [330]:
x = np.arange(5)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)   # modulo

x     = [0 1 2 3 4]
x + 5 = [5 6 7 8 9]
x - 5 = [-5 -4 -3 -2 -1]
x * 2 = [0 2 4 6 8]
x / 2 = [0.  0.5 1.  1.5 2. ]
x // 2 = [0 0 1 1 2]
-x     =  [ 0 -1 -2 -3 -4]
x ** 2 =  [ 0  1  4  9 16]
x % 2  =  [0 1 0 1 0]


These operators are actually wrappers to the method form:

In [333]:
np.add(x,5)

array([5, 6, 7, 8, 9])

In [335]:
np.floor_divide(x,2)

array([0, 0, 1, 1, 2])

More functions like this can be found in the documentation of the <a href="https://www.numpy.org/devdocs/reference/ufuncs.html#available-ufuncs" target="_blank">uFuncs</a> .

### Trigonometric functions

Numpy can compute mathematical functions very efficiently over a large array. They are computed to withon machine precision, therefore tiny values instead of exact zeros can appear.

In [342]:
# An array of 3000 elements between 0 and Pi.
theta = np.linspace(0, np.pi, 3000)
print("theta      = ", theta[0])
print("sin(theta) = ", np.sin(theta)[-1])
print("cos(theta) = ", np.cos(theta)[0])
print("tan(theta) = ", np.tan(theta)[-1])

theta      =  0.0
sin(theta) =  1.2246467991473532e-16
cos(theta) =  1.0
tan(theta) =  -1.2246467991473532e-16


Numpy also offers mathematical functions like `exp` and `log` and versions that are more accurate for tiny numbers, like **`expm1`** and **`log1p`**. 

In [343]:
# For tiny x values, log(1+x) and exp(x)-1 are very very close to x.
x = np.array([0., 1e-10, 1e-12, 1e-14])
print("     exp(x) - 1 =", np.expm1(x))
print("std: exp(x) - 1 =", np.exp(x)-1.0)
print("     log(1 + x) =", np.log1p(x))
print("std: log(1 + x) =", np.log(1.0+x))

     exp(x) - 1 = [0.e+00 1.e-10 1.e-12 1.e-14]
std: exp(x) - 1 = [0.00000000e+00 1.00000008e-10 1.00008890e-12 9.99200722e-15]
     log(1 + x) = [0.e+00 1.e-10 1.e-12 1.e-14]
std: log(1 + x) = [0.00000000e+00 1.00000008e-10 1.00008890e-12 9.99200722e-15]


There are tons of functionalities more, but this is just a rough overview. In the documentation and many other excellent tutorials and books, such as the 
    <a href="https://jakevdp.github.io/PythonDataScienceHandbook/"  target="_blank">Python Data Science Handbook</a>  one can find much more on these topics.

## Slowness of loops and lists vs. Numpy 

In a standard programming language, like C, we would have to define the following non-pythonic function in order to compute the reciprocal of a list

In [371]:
def compute_reciprocals(values):
    output = []
    for i in range(len(values)):
        output.append(1.0 / values[i])
    return output

In [384]:
a_list = np.random.randint(1,10,10000000).tolist()  #notice the tolist method here
print(a_list[0])

4


Computing the reciprocal will be slow, since each element of the python list is a data structure object.

In [382]:
%%time
b_list = compute_reciprocals(a_list)
#print(b_list[0])

CPU times: user 900 ms, sys: 69.8 ms, total: 970 ms
Wall time: 969 ms


In [376]:
a_array = np.random.randint(1,10,10000000)

In Numpy we don't even need to define a function, we just calculate 1.0/list.

In [383]:
%%time
b_array = 1.0 / a_array
#print(b_array)

CPU times: user 30.7 ms, sys: 20.9 ms, total: 51.6 ms
Wall time: 50.2 ms


## Broadcasting and fancy indexing